baseURL = 'brentjayingram.dev'
languageCode = 'en-us'
title = 'Brent Jay Ingram'
theme = 'paige'

baseurl = "https://example.com"
copyright = "© Michael Bluth"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[languages.en]
title = "No Borders, No Limits"
weight = 10

[[params.paige.figure]]
src="https://imgs.xkcd.com/comics/sandwich.png"
link="https://xkcd.com/149"
caption="My caption"
title="My title"
alt="My alt" 
height= 500

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30

[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 40

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 60

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "vs"

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2


[outputs]
home = [ "html", "json", "rss" ]



[params.paige.social.email]
icon = "envelope"
link = "mailto:username@example.com"
name = "E-mail"


[params.paige.social.github]
icon = "github"
link = "https://github.com/username"
name = "GitHub"

[params.paige.social.linkedin]
icon = "linkedin"
link = "https://linkedin.com/in/username"
name = "LinkedIn"

[params.paige.social.instagram]
icon = "instagram"
link = "https://instagram.com/username"
name = "Instagram"



[permalinks]
blog = "/blog/:year/:month/:day/:title/"


